all:
	gcc -ansi -pedantic -Wall -o Ex1a.exe Ex1a.c
	gcc -ansi -pedantic -Wall -o Ex1c.exe Ex1c.c
	gcc -ansi -pedantic -Wall -o Ex1d.exe Ex1d.c
	gcc -ansi -pedantic -Wall -o Ex1e.exe Ex1e.c
	gcc -ansi -pedantic -Wall -o Ex1f.exe Ex1f.c
	gcc -ansi -pedantic -Wall -o Ex2.exe Ex2.c
	gcc -ansi -pedantic -Wall -o Ex3.exe Ex3.c

clean:
	rm *.exe
