all:
	gcc -ansi -pedantic -Wall -o module6_1.exe module6_1.c
	gcc -ansi -pedantic -Wall -o module6_2.exe module6_2.c
	gcc -ansi -pedantic -Wall -o module6_3.exe module6_3.c
	gcc -ansi -pedantic -Wall -o module6_prob1.exe module6_prob1.c
	gcc -ansi -pedantic -Wall -o module6_prob2.exe module6_prob2.c
	gcc -ansi -pedantic -Wall -o module6_prob3.exe module6_prob3.c

clean:
	rm *.exe
